export const MONGO_CLIENT = 'MONGO_CLIENT';
export const MONGO_DB = 'MONGO_DB';
export const USER_COLLECTION = 'USER_COLLECTION';
export const PHISHING_COLLECTION = 'PHISHING_COLLECTION';
export const SESSION_COLLECTION = 'SESSION_COLLECTION';
